//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_test
    {
        public int no { get; set; }
        public int flag { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
